Detail social links
interglobalvision/insearchofthetruth-net pull request #69
Opened 2017-12-11 23:55 UTC by mikeyrayvon

adds social link in header and mobile menus

2017-12-12 23:02 UTC, varffs requested changes
I'm pretty sure that is just a typo. Feel free to merge after that as it is fine

2017-12-12 23:02 UTC, varffs commented on src/styl/responsive/tablet-portrait.styl
> +  margin: 0 0 .8em 0
I think one of these `0` is extra? On my local it looks proper with .8em left and right not just bottom?

2017-12-14 16:37 UTC, mikeyrayvon commented
yea it was a typo. meant it to be margin left

2017-12-18 19:33 UTC, varffs approved these changes

2017-12-18 19:35 UTC, merged